development:
  facebook:
    app_id: "303232736429925"
    app_secret: "ebe99065439676ed8f75059927dae8ac"
    options:
      scope: "email"
      display: "page"

staging: &staging
  facebook:
    app_id: "378201315578308"
    app_secret: "4dabe290bd8ad7f815c54ad708141057"
    options:
      scope: "email"
      display: "page"

test:
  <<: *staging

production:
  facebook:
    app_id: ""
    app_secret: ""